defaults: &defaults
  working_directory: ~/build

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: node:12.18.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
        environment:
          TEST_REPORT_PATH: reports/npm-test.txt
      - image: mongo:4.0

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.05.0-ce

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Installing NPM Modules
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Executing Tests
          command: |
            mkdir reports
            npm test | tee ${TEST_REPORT_PATH}
            cp -r coverage/ reports/

      - store_artifacts:
          path: reports

workflows:
  version: 2
  automated-deploy-process:
    jobs:
      - build:
          context: brandao