defaults: &defaults
  working_directory: ~/build

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
        environment:
          TEST_REPORT_PATH: reports/npm-test.txt
      - image: mongo:4.0

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.05.0-ce

      - run:
          name: Installing NPM Modules
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Executing Tests
          command: |
            mkdir reports
            npm test | tee ${TEST_REPORT_PATH}
            cp -r coverage/ reports/
      - run:
          name: Building and Publishing Image
          command: |
            TAG=$(node -p -e "require('./package.json').version")            
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

            echo "building image"
            docker build -t lucasbrandao/whats-song:$TAG ./ | tee $BUILD_REPORT_PATH
            echo "pushing image $IMAGE:$TAG" | tee $BUILD_REPORT_PATH
            
            docker push lucasbrandao/whats-song:$TAG | tee -a $BUILD_REPORT_PATH
            echo "Image lucasbrandao/whats-song:$TAG published on docker hub!"
      - store_artifacts:
          path: reports

workflows:
  version: 2
  automated-deploy-process:
    jobs:
      - build:
          context: brandao
